version: '2.2'

services:
    bemodule:
      container_name: budgetcontrol-ms-name
      image: mlabfactory/php8-apache:v1.2-xdebug
      volumes:
        - ./:/var/www/workdir
      networks:
        - budgetcontrol_network
      restart: unless-stopped
      ports:
        - "****:80"

networks:
  budgetcontrol_network:
    external: false
    name: budgetcontrol_network
